e_news/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('index.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS[0])
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

index/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.home_page, name='home_page'),
    path('news/<int:pk>/', views.news_page, name='news_page'),
    path('category/<int:pk>/', views.category_page, name='category_page'),
    path('categories/', views.category_list, name='category_list'),
    path('register/', views.Register.as_view(), name='register'),
    path('search/', views.search, name='search'),
    path('favorites/', views.view_favorites, name='view_favorites'),
    path('favorites/add/', views.add_to_favorites, name='add_to_favorites'),
    path('favorites/remove/', views.remove_from_favorites, name='remove_from_favorites'),
]

index/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
# Таблица категорий
class NewsCategory(models.Model):
    title = models.CharField("Название категории", max_length=64)
    created_at = models.DateTimeField("Дата добавления", auto_now_add=True)

    def __str__(self):
        return self.title


# Таблица новостей
class News(models.Model):
    title = models.CharField("Заголовок", max_length=512)
    content = models.TextField("Основной текст")
    category = models.ForeignKey(NewsCategory, on_delete=models.CASCADE)
    created_at = models.DateTimeField("Дата добавления", auto_now_add=True)

    def __str__(self):
        return self.title

    def add_to_favorite(self, user):
        FavoriteNews.objects.get_or_create(user=user, news=self)

    def remove_from_favorite(self, user):
        FavoriteNews.objects.filter(user=user, news=self).delete()

    def is_favorite(self, user):
        return FavoriteNews.objects.filter(user=user, news=self).exists()


# Избранные новости
class FavoriteNews(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    news = models.ForeignKey(News, on_delete=models.CASCADE)
    added_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        constraints = [
            models.UniqueConstraint(fields=['user', 'news'], name='unique_favorite_news')
        ]

    def __str__(self):
        return f"{self.user.username} - {self.news.title}"

index/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class RegForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

index/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import NewsCategory, News, FavoriteNews
from .forms import RegForm
from django.views import View
from django.contrib.auth import login, logout
from django.contrib.auth.models import User
from django.urls import reverse
from django.contrib import messages
from django.contrib.auth.decorators import login_required


# Create your views here.
# Главная страница
def home_page(request):
    # Достаем данные из БД
    category = NewsCategory.objects.all()
    news = News.objects.all()
    # Передаем данные на frontend
    context = {'category': category, 'news': news}

    return render(request, 'index/home.html', context)


def category_list(request):
    # Достаем все категории из БД
    category = NewsCategory.objects.all()
    news_list = News.objects.all()
    # Передаем данные на frontend
    context = {'categories': category, 'news_list': news_list}
    return render(request, 'index/category_list.html', context)


# Вывод новости по выбранной категории
def category_page(request, pk):
    # Достаем выбранную категорию
    category = NewsCategory.objects.get(id=pk)
    # Фильтруем новости по категории
    news = News.objects.filter(category=category)
    # Данные для сайдбара
    news_list = News.objects.all()
    categories = NewsCategory.objects.all()
    # Передаем данные на frontend
    context = {'category': category, 'news': news, 'news_list': news_list, 'categories': categories}

    return render(request, 'index/category.html', context)


# Вывод определенной новости
def news_page(request, pk):
    # Вывод выбранной новости
    news = News.objects.get(id=pk)
    # Данные для сайдбара
    news_list = News.objects.all()
    categories = NewsCategory.objects.all()
    # Передаем данные на frontend
    context = {'news': news, 'news_list': news_list, 'categories': categories}

    return render(request, 'index/news.html', context)


# Регистрация
class Register(View):
    template_name = 'registration/register.html'

    # Выдача формы
    def get(self, request):
        context = {'form': RegForm}
        return render(request, self.template_name, context)

    # Получение ифны с формы
    def post(self, request):
        form = RegForm(request.POST)

        # Если данные корректны
        if form.is_valid():
            username = form.clean_username()
            email = form.cleaned_data.get('email')
            password = form.cleaned_data.get('password2')

            # Объект класса User
            user = User.objects.create_user(username=username,
                                            email=email,
                                            password=password)
            user.save()

            # Авторизуем пользователя
            login(request, user)
            return redirect('/')
        # Если данные некорректны
        context = {'form': RegForm, 'message': 'Пароль или почта неверны!'}
        return render(request, self.template_name, context)


# Выход из аккаунта
def logout_view(request):
    logout(request)
    return redirect('/')


# Поиск
def search(request):
    query = request.GET.get('q', '').strip()

    if query:
        matching_news = News.objects.filter(title__icontains=query)

        if matching_news.exists():
            return redirect(reverse('news_page', args=[matching_news.first().id]))
        else:
            messages.error(request, f"К сожалению, ничего не найдено по запросу: '{query}'.")
            return redirect(reverse('home_page'))
    else:
        messages.warning(request, "Введите текст для поиска.")
        return redirect(reverse('home_page'))


# Добавление в избранное
@login_required
def add_to_favorites(request):
    if request.method == 'POST':
        news_id = request.POST.get('news_id')
        user = request.user
        news = get_object_or_404(News, id=news_id)

        if not FavoriteNews.objects.filter(user=user, news=news).exists():
            FavoriteNews.objects.create(user=user, news=news)
            messages.success(request, 'Новость добавлена в избранное!')
        else:
            messages.warning(request, 'Эта новость уже в избранном.')

    return redirect(request.META.get("HTTP_REFERER", "/"))


# Удаление из избранного
@login_required
def remove_from_favorites(request):
    if request.method == 'POST':
        news_id = request.POST.get('news_id')
        user = request.user

        deleted = FavoriteNews.objects.filter(user=user, news_id=news_id).delete()
        if deleted[0] > 0:
            messages.success(request, 'Новость удалена из избранного.')
        else:
            messages.warning(request, 'Этой новости не было в избранном.')

    return redirect(request.META.get("HTTP_REFERER", "/"))


# Функция для отображения избранных новостей
@login_required
def view_favorites(request):
    user = request.user
    # Получаем все избранные новости для текущего пользователя
    favorite_news = FavoriteNews.objects.filter(user=user).select_related('news')
    # Передаем их в шаблон
    return render(request, 'index/favorites.html', {'favorite_news': favorite_news})

index/templates/index/category.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Новости</title>
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>

    <div class="d-flex">
        <header>
            <div class="header-left">
                <h1>Новости поп культуры</h1>
            </div>
                <!-- Кнопки -->
                <div class="auth-buttons">
                    <a href="{% url 'login' %}" class="btn login-btn">Войти</a>
                    <a href="{% url 'register' %}" class="btn register-btn">Регистрация</a>
                </div>
                <!-- Поиск-->
                <form action="{% url 'search' %}" method="get" class="search-form">
                    <input type="text" name="q" placeholder="Поиск новостей..." class="search-input" value="{{ request.GET.q|default_if_none:'' }}">
                    <button type="submit" class="search-btn">Поиск</button>
                </form>
        </header>

        <!-- Сообщение "Не найдено по запросу" -->
        {% if messages %}
            <div class="messages">
                {% for message in messages %}
                    <p class="message {{ message.tags }}">{{ message }}</p>
                {% endfor %}
            </div>
        {% endif %}

        <!-- Sidebar -->
        <aside class="sidebar">
            <a href="{% url 'home_page' %}" class="btn btn-home">Главная</a>
            <a href="{% url 'category_list' %}" class="btn btn-home">Категории</a>
            <a href="{% url 'view_favorites' %}" class="btn btn-home">Избранное</a>
            <h2>Последние новости</h2>
            <ul class="news-list">
                {% for item in latest_news %}
                    <li>
                        <a href="{% url 'news_page' item.id %}">{{ item.title }}</a>
                    </li>
                {% empty %}
                    <li>Нет новостей для отображения.</li>
                {% endfor %}
            </ul>
        </aside>

        <!-- Главный контент -->
        <div class="main-content">
            <h2>Новости в категории "{{ category.title }}"</h2>
            {% for item in news %}
                <div class="news-item">
                    <h3 class="news-title">{{ item.title }}</h3>
                    <p class="news-content">{{ item.content|truncatechars:100 }}</p>
                    <p class="news-category">Категория: {{ item.category.title }} | Дата: {{ item.created_at|date:"d.m.Y" }}</p>
                    <a href="{% url 'news_page' item.id %}">Читать дальше</a>
                </div>
            {% empty %}
                <p>Новостей пока нет в этой категории.</p>
            {% endfor %}
        </div>
    </div>

</body>
</html>

index/templates/index/category_list.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Категории новостей</title>
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>
    <header>
        <h1>Новости поп культуры</h1>
    </header>

    <div class="d-flex">
        <!-- Sidebar -->
        <div class="col-md-3">
            <aside class="sidebar">
                <a href="{% url 'home_page' %}" class="btn btn-home">Главная</a>
                <a href="{% url 'category_list' %}" class="btn btn-category-list">Категории</a>
                <h2>Категории</h2>
                <ul class="category-list">
                    {% for category in categories %}
                        <li>
                            <a href="{% url 'category_page' category.id %}">{{ category.title }}</a>
                        </li>
                    {% empty %}
                        <li>Нет категорий для отображения.</li>
                    {% endfor %}
                </ul>
                <h2>Последние новости</h2>
                <ul class="news-list">
                    {% for item in news_list %}
                        <li>
                            <a href="{% url 'news_page' item.id %}">{{ item.title }}</a>
                        </li>
                    {% empty %}
                        <li>Нет новостей для отображения.</li>
                    {% endfor %}
                </ul>
            </aside>
        </div>

        <!-- Главный контент -->
        <div class="main-content">
            <h2>Список категорий</h2>
            {% for category in categories %}
                <div class="news-item">
                    <!-- Category Title -->
                    <h3 class="news-title">{{ category.title }}</h3>
                    <p class="news-category">Количество новостей: {{ category.news_set.count }}</p>

                    <!-- Button to Open Category -->
                    <a href="{% url 'category_page' category.id %}" class="news-item">Открыть</a>
                </div>
            {% empty %}
                <p>Нет категорий для отображения.</p>
            {% endfor %}
        </div>
    </div>

</body>
</html>

index/templates/index/favorites.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Новости</title>
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>

    <div class="d-flex">
        <header>
            <div class="header-left">
                <h1>Новости поп культуры</h1>
            </div>
                <!-- Кнопки -->
                <div class="auth-buttons">
                    <a href="{% url 'login' %}" class="btn login-btn">Войти</a>
                    <a href="{% url 'register' %}" class="btn register-btn">Регистрация</a>
                </div>
                <!-- Поиск-->
                <form action="{% url 'search' %}" method="get" class="search-form">
                    <input type="text" name="q" placeholder="Поиск новостей..." class="search-input" value="{{ request.GET.q|default_if_none:'' }}">
                    <button type="submit" class="search-btn">Поиск</button>
                </form>
        </header>

        <!-- Сообщение "Не найдено по запросу" -->
        {% if messages %}
            <div class="messages">
                {% for message in messages %}
                    <p class="message {{ message.tags }}">{{ message }}</p>
                {% endfor %}
            </div>
        {% endif %}

        <!-- Sidebar -->
        <aside class="sidebar">
            <a href="{% url 'home_page' %}" class="btn btn-home">Главная</a>
            <a href="{% url 'category_list' %}" class="btn btn-home">Категории</a>
            <a href="{% url 'view_favorites' %}" class="btn btn-home">Избранное</a>
            <h2>Последние новости</h2>
            <ul class="news-list">
                {% for item in latest_news %}
                    <li>
                        <a href="{% url 'news_page' item.id %}">{{ item.title }}</a>
                    </li>
                {% empty %}
                    <li>Нет новостей для отображения.</li>
                {% endfor %}
            </ul>
        </aside>

        <!-- Главный контент -->
        <div class="main-content">
            <h2>Избранные новости</h2>
            {% for item in favorite_news %}
                <div class="news-item">
                    <h3 class="news-title">{{ item.news.title }}</h3>
                    <p class="news-content">{{ item.news.content|truncatechars:128 }}</p>
                    <p class="news-category">Категория: {{ item.news.category.title }} | Дата: {{ item.news.created_at|date:"d.m.Y" }}</p>
                    <a href="{% url 'news_page' item.news.id %}">Читать дальше</a>
                    <form action="{% url 'remove_from_favorites' %}" method="post">
                        {% csrf_token %}
                        <input type="hidden" name="news_id" value="{{ item.news.id }}">
                        <button type="submit" class="btn btn-remove">Удалить из избранного</button>
                    </form>
                </div>
            {% empty %}
                <p>Вы еще не добавили новости в избранное.</p>
            {% endfor %}
        </div>
    </div>
</body>
</html>

index/templates/index/home.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Новости</title>
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>

    <div class="d-flex">
        <header>
            <div class="header-left">
                <h1>Новости поп культуры</h1>
            </div>
                <!-- Кнопки -->
                <div class="auth-buttons">
                    <a href="{% url 'login' %}" class="btn login-btn">Войти</a>
                    <a href="{% url 'register' %}" class="btn register-btn">Регистрация</a>
                </div>
                <!-- Поиск-->
                <form action="{% url 'search' %}" method="get" class="search-form">
                    <input type="text" name="q" placeholder="Поиск новостей..." class="search-input" value="{{ request.GET.q|default_if_none:'' }}">
                    <button type="submit" class="search-btn">Поиск</button>
                </form>
        </header>

        <!-- Сообщение "Не найдено по запросу" -->
        {% if messages %}
            <div class="messages">
                {% for message in messages %}
                    <p class="message {{ message.tags }}">{{ message }}</p>
                {% endfor %}
            </div>
        {% endif %}

        <!-- Sidebar -->
        <aside class="sidebar">
            <a href="{% url 'home_page' %}" class="btn btn-home">Главная</a>
            <a href="{% url 'category_list' %}" class="btn btn-home">Категории</a>
            <a href="{% url 'view_favorites' %}" class="btn btn-home">Избранное</a>
            <h2>Последние новости</h2>
            <ul class="news-list">
                {% for item in latest_news %}
                    <li>
                        <a href="{% url 'news_page' item.id %}">{{ item.title }}</a>
                    </li>
                {% empty %}
                    <li>Нет новостей для отображения.</li>
                {% endfor %}
            </ul>
        </aside>


        <!-- Главный контент -->
        <div class="main-content">
            <h2>Новости</h2>
            {% for item in news %}
                <div class="news-item">
                    <h3 class="news-title">{{ item.title }}</h3>
                    <p class="news-content">{{ item.content|truncatechars:128 }}</p>
                    <p class="news-category">Категория: {{ item.category.title }} | Дата: {{ item.created_at|date:"d.m.Y" }}</p>
                    <a href="{% url 'news_page' item.id %}">Читать дальше</a>
                </div>
            {% empty %}
                <p>Новостей пока нет.</p>
            {% endfor %}
        </div>
    </div>

</body>
</html>

index/templates/index/news.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Новости</title>
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>

    <div class="d-flex">
        <header>
            <div class="header-left">
                <h1>Новости поп культуры</h1>
            </div>
                <!-- Кнопки -->
                <div class="auth-buttons">
                    <a href="{% url 'login' %}" class="btn login-btn">Войти</a>
                    <a href="{% url 'register' %}" class="btn register-btn">Регистрация</a>
                </div>
                <!-- Поиск-->
                <form action="{% url 'search' %}" method="get" class="search-form">
                    <input type="text" name="q" placeholder="Поиск новостей..." class="search-input" value="{{ request.GET.q|default_if_none:'' }}">
                    <button type="submit" class="search-btn">Поиск</button>
                </form>
        </header>

        <!-- Sidebar -->
        <aside class="sidebar">
            <a href="{% url 'home_page' %}" class="btn btn-home">Главная</a>
            <a href="{% url 'category_list' %}" class="btn btn-home">Категории</a>
            <a href="{% url 'view_favorites' %}" class="btn btn-home">Избранное</a>
            <h2>Последние новости</h2>
            <ul class="news-list">
                {% for item in latest_news %}
                    <li>
                        <a href="{% url 'news_page' item.id %}">{{ item.title }}</a>
                    </li>
                {% empty %}
                    <li>Нет новостей для отображения.</li>
                {% endfor %}
            </ul>
        </aside>

            <!-- Главный контент -->
            <div class="col-md-9 main-content">
                <article class="news-item">
                    <h1>{{ news.title }}</h1>
                    <div class="news-content">
                        <p>{{ news.content }}</p>
                    </div>
                    <div class="news-meta">
                        <p class="category">Категория: {{ news.category.title }}</p>
                        <p class="date">Дата: {{ news.created_at|date:"d.m.Y" }}</p>
                    </div>

                    <!-- Отображение сообщений -->
                    {% if messages %}
                        <ul class="messages">
                            {% for message in messages %}
                                <li class="{{ message.tags }}">{{ message }}</li>
                            {% endfor %}
                        </ul>
                    {% endif %}

                    <!-- Кнопка избранного -->
                    <form action="{% if is_favorite %}{% url 'remove_from_favorites' %}{% else %}{% url 'add_to_favorites' %}{% endif %}" method="post">
                        {% csrf_token %}
                        <input type="hidden" name="news_id" value="{{ news.id }}">
                        <button type="submit" class="btn btn-favorite">
                            {% if is_favorite %}Удалить из избранного{% else %}Добавить в избранное{% endif %}
                        </button>
                    </form>

                    <div class="back-link">
                        <a href="{% url 'category_page' news.category.id %}" class="btn btn-back">Назад</a>
                    </div>
                </article>
            </div>
        </div>
    </div>
</body>
</html>